### ISSUE TITLE
barcode mismatch correction

### ISSUE THREAD

**Issue by roryk** [vals/umis#20]
Hi Valentine,

What do you think about sticking some code in there to optionally find barcodes 1 or 2 edit distances away from the known barcodes and correcting them? I think we can do up to two edit distances pretty efficiently and simply. I'm down for implementing it if that sounds ok to you.

**Comment by vals** [comment]
Hey Rory,

I wouldn't mind having it in if it is something you'd like. Especially if you implement it :).

I'm just curious if you tend to find this being a problem? I rarely see more than ~4% of reads not falling on to a-priori known barcodes when we have these (in e.g. STRT-Seq or CEL-Seq), which I think is comparable to standard Illumina demultiplexing.

**Comment by roryk** [comment]
Sweet, I'll get on it. It usually isn't a problem, but some of the preps we are working with have enzymes that have a bias for a particular nucleotide at the start or end, and we lose like 30% or more by only keeping exact matches.
