### ISSUE TITLE
Can you include a License file for the umis repository, please?

### ISSUE THREAD

**Issue by tomsing1** [vals/umis#4]
Including a license file makes it clear if / how your code can be reused by others. Thanks a lot!

**Comment by vals** [comment]
Ok, what is one that is roughly equivalent to public domain?

**Comment by roryk** [comment]
MIT license is a "do whatever you want with this, just don't sue me and give me some props." license:

https://tldrlegal.com/license/mit-license

**Comment by vals** [comment]
Ok, I'll trust your judgement regarding MIT :)
