### ISSUE TITLE
Adjusting for Poisson counting statistics

### ISSUE THREAD

**Issue by ghost** [vals/umis#41]
Hi,

I was wondering if you are adjusting for Poisson counting statistics, when the length of the molecular UMI barcode is short. Some of the recent UMI protocols (e.g. Muraro, Cell Systems 2016) only use 4 bases long random UMI barcodes to tag transcripts. This makes only 256 possible UMIs, so that different transcripts will often have the same UMI bar code. The expected number of transcripts can thus be inferred from the number of UMIs with Poisson Counting statistics. For example if we see all 256 possible UMI, we expect at least 1597 transcripts. I have data of this kind at the moment and I am wondering if I can use the bc_bioc pipeline for it. Thanks!

Alexander

PS: If this is not part of the pipeline, I am not sure if it is worth adding it, as future protocols will hopefully have longer barcodes anyways.

**Comment by roryk** [comment]
HI Alexander,

Thanks for the question. That is an interesting way to try to expand the range a little bit. We don't do anything fancy like that with the UMI unfortunately so if you ran it through bcbio you'd be dealing with a compressed range. Hopefully they'll stick a few more nucleotides on the UMI in future iterations of the protocols.

**Comment by vals** [comment]
Hi Alexander,

I would also say this is something which should be done in the downstream analysis of the count table.

Personally I don't attempt to quantify precisely how many molecules there were in the data in my analysis, but if this is the goal, you're right that this correction is important.
