### ISSUE TITLE
During Filtering noise celluar barcodes

### ISSUE THREAD

**Issue by hansparkdgist** [vals/umis#45]
Is it taking a long time originally? So I did with multi core option, but it doesn't work.
![image](https://user-images.githubusercontent.com/31980326/31751205-2927c5b4-b4bf-11e7-8857-d742c9ddd977.png)
![image](https://user-images.githubusercontent.com/31980326/31751216-379ea0fe-b4bf-11e7-8b10-845122526627.png)

**Comment by roryk** [comment]
Sorry we never commented on this, hope you got it straightened out.
