### ISSUE TITLE
Avoid expanding collapsed counts

### ISSUE THREAD

**Issue by vals** [vals/umis#47]
Hi @roryk,

I don't know if you have noticed, but at some point during `tagcount`ing, the RAM usage expands rapidly. This causes issues of e.g. cluster nodes quitting due to reaching RAM limits.

I haven't had time to profile this, but I suspect the culprit is this bit:

```
    evidence_query = 'evidence >= %f' % minevidence
    if positional:
        evidence_table.columns=['cell', 'gene', 'umi', 'pos', 'evidence']
        collapsed = evidence_table.query(evidence_query).groupby(['cell', 'gene'])['umi', 'pos'].size()

    else:
        evidence_table.columns=['cell', 'gene', 'umi', 'evidence']
        collapsed = evidence_table.query(evidence_query).groupby(['cell', 'gene'])['umi'].size()

    expanded = collapsed.unstack().T
```

The `.unstack()` here basically takes a sparse matrix and turns it into a dense matrix.

I think it makes more sense to just reformat the `collapsed` table to a COO sparse matrix, and save those values. At least when run using the `--sparse` flag.

Would you have any objection to this? Or do you know if the memory explosion is due to something else?

**Comment by roryk** [comment]
Hi @vals,

I've definitely noticed it; on higher read depth samples the explosion is before that step though. The reason why is the hash table of e_tuples gets huge and ends up having a bajillion collisions in it and it explodes in size. I rewrote the tag counting, there is a fasttagcount subcommand now that relies on the fact the sample is indexed and goes transcript by transcript which uses about 1/100th of the memory.

**Comment by vals** [comment]
Oh interesting! I didn't notice that!

I'll check that out and also tell others (cc @tomasgomes ) to try that command instead.

It writes a CSV which I guess you typically run the `sparse` command on then?

It might be time updating the `README` putting in the full workflow in this mode. Our _ad hoc_ solution has been to split the `cb_hist` argument to multiple compute nodes, this is much better.

Do you do `fastqtransform` -> `RapMap` -> `samtools sort` -> `samtools index` -> `fasttagcount`?

**Comment by roryk** [comment]
Hi @vals,

Yup, that's right. I think it might not handle cases where genes are never seen, like it won't report those genes but it should. it would be good to fix that if it is the case.

**Comment by vals** [comment]
This could maybe be implicitly handled by writing directly to a COO sparse matrix format. You would need to provide a full gene list as input, but then you output the integer encoding the gene instead. In this case the 0's will be treated as missing values either way, and be filled in when you read the sparse matrix file.

**Comment by roryk** [comment]
That would be great to not have the CSV intermediate and just do everything in sparse mode.
