### ISSUE TITLE
valid cellular barcodes

### ISSUE THREAD

**Issue by roryk** [vals/umis#48]
What do you think about including valid cellular barcodes for the different chemistries in this repository? They can be a couple MB in size but it would be nice if everything you needed to run through 10x or whatever was all in one place instead of having to hunt around for the pieces.

**Comment by vals** [comment]
I think it should be fine. Have a look first how large they are after compressing or so, maybe they are tiny which would be great. We could make it so that any command that uses them uncompresses them on the fly.

They would go well into the Examples directory, like you did with SureCell.
