### ISSUE TITLE
error in umis cb_filter

### ISSUE THREAD

**Issue by Dragonlongzhilin** [vals/umis#49]
I used the umi fastqtransform to formatted read and it's ok.
The formatting reads is 
![image](https://user-images.githubusercontent.com/33304280/38858934-8c3f0620-425f-11e8-9359-cd1387078675.png)
But when I use the umis cb_filter  command to filter cell barcode, it's error:
command : umis cb_filter SRR1058003.fastq
error
![image](https://user-images.githubusercontent.com/33304280/38859252-31ec963c-4260-11e8-9a71-132e5744bafc.png)
what happened?

**Comment by roryk** [comment]
Hi @Dragonlongzhilin,

The `cb_filter` subcommand needs a set of known cellular barcodes to keep; it looks like you just have the one so if you pass in the set of known cellular barcodes with `--bc1 your-barcode-list.txt` this will work. I pushed a fix to make `--bc1` a required argument so it will give a more informative error message.

**Comment by roryk** [comment]
Thanks!

**Comment by Dragonlongzhilin** [comment]
@roryk, Thank you for your reply
How do I get the barcode-list.txt?
Is it right that I extract the cell barcde to construct the barcode-list file from my fastq file?

**Comment by roryk** [comment]
Hi @Dragonlongzhilin,

You'd have to know that from whatever library prep you did; some chemistries don't have known cellular barcodes going in, some do.

**Comment by Dragonlongzhilin** [comment]
Hi @roryk ,
The library protocol of my data is SCRB-seq.
I known the the read 2 contains the transcript sequence and read 1 the cell(first 6bp) and UMI barcodes(7-16bp).
like that:
![image](https://user-images.githubusercontent.com/33304280/38906288-529a8f5a-42e8-11e8-8593-7238635a7dad.png)
Can I produce the barcode-list.txt directly from the read1 file?

**Comment by roryk** [comment]
Hi @Dragonlongzhilin,

For SCRB-seq, the input cellular barcodes are known, so someone should have told you what the set of possible cellular barcodes is.  Whoever made the library will know that information. The purpose of `cb_filter` is to look at the reads in the FASTQ file and compare them to he set of known cellular barcodes and remove reads which do not have a known cellular barcode. So if you don't know the known cellular barcodes, `cb_filter` won't do anything.

**Comment by Dragonlongzhilin** [comment]
Thanks, it's helpful for me!
