### ISSUE TITLE
ddseq SureCell

### ISSUE THREAD

**Issue by sgmccalla** [vals/umis#50]
Hi,
Could you please provide a submission example of processing ddseq data with the umis fastqtransform command? I am not sure which flag to use for the barcodes.txt file:
https://github.com/vals/umis/tree/master/examples/SureCell

This is what I have so far:
umis fastqtransform transform.json K562_R1.fastq --fastq1out S2_out

Thank you

**Comment by vals** [comment]
Hi Sunnie,

The command used for transforming in this example is 

```
umis fastqtransform \
--separate_cb \
examples/SureCell/transform.json \
examples/SureCell/K562_R1.fastq \
examples/SureCell/K562_R2.fastq \
> tests/results/test21.fq
```

(In general running command examples can be found in https://github.com/vals/umis/blob/master/test.sh )

The `barcodes.txt` file is used downstream of this if you want to filter your detected barcodes against this known whitelist. 

In this particular case, the command to do this will be 

```
umis cb_filter \
     --nedit 1 \
     --bc1 examples/SureCell/barcodes.txt \
     --bc2 examples/SureCell/barcodes.txt \
     --bc3 examples/SureCell/barcodes.txt \
     tests/results/test21.fq \
     > tests/results/test21-filtered.fq
```

Though if you run the transform on real data, I would recommend also comparing the CB histogram generated with `umis cb_histogram` with the whitelist. This can be a useful QC step to make sure your library worked correctly.

Does this help?

/Valentine

**Comment by sgmccalla** [comment]
Thank you very much Valentine, that really helps.
