### ISSUE TITLE
So slow when cb_filter

### ISSUE THREAD

**Issue by eleven919** [vals/umis#51]
Hi,

I am using umis to analyze our single-cell data from 10x genomics, the fastqtransform step is OK but it is extremely slow when I run cb_filter option.

I have downloaded all cell barcode list (around 737k) from Cell Ranger package, do you have some good ideas to speed it up (around 14M reads)? I already try multiple cores but it did improve too much.

Thanks in advance!

**Comment by roryk** [comment]
Heya,

If you have —nedit set up to be non-zero, then with 737k possible barcodes umis will set it up to have all edits from 1 from those barcodes be a possible barcode. I think that is causing there to be a huge dictionary of possible barcodes, which is having lots of collisions while making it. I’m guessing the memory usage is blowing up with that many entries.

If you’re ok with losing some reads, if you set —nedit to 0 it should go much faster. Barring that, we’d have to re-think the data structure we are using the to do the barcode correction to handle lists with this many barcodes.

Best,

Rory

**Comment by eleven919** [comment]
Hi Rory,

Thank you so much for your quick reply. Yes, the nedit is 1 in my command, I will try to set it to 0 because the speed with 1 nedit is really crazy.

Thx again and look forward to your successor.

Qiang
