### ISSUE TITLE
Multi-maps

### ISSUE THREAD

**Issue by ivlachos** [vals/umis#54]
Hello,

I'm testing the pipeline and I was wondering how are multi-mapping reads handled.

I'm currently using Salmon sam output and RapMap, where I have a large fraction of the reads non-uniquely assigned (which is expected). 

Does the pipeline count only uniquely aligned or will count the multimapping read if the UMI for the region in question is unique? Will the sum of all counts be larger than the input?

Thanks!

**Comment by roryk** [comment]
Hi @ivlachos,

For a read that aligns to N transcripts, each of the N transcripts is given evidence of 1/N for that read. Then at the end totals with evidence < 1 are rounded down to 0, and everything else is rounded.

**Comment by ivlachos** [comment]
Thank you for the lightning-fast response!

**Comment by roryk** [comment]
No problem!
