### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by magali** [vals/umis#56]
Hello,

I'm using umis on an administered server. The install does not work properly (see Closed Issue #55).

I know that the install can work with bioconda, but the admins do not want to use conda install, only pip.

Is there any way you can make the pip install work so we can have a working version on our server?

Thanks,
Magali

**Comment by roryk** [comment]
Hi Magali,

I don't have access to update what's on pypi-- @vals, could you bump to the latest version?

In the meantime, the admins can install it with pip if they want like this:

`pip install git+https://github.com/vals/umis.git@master`

**Comment by vals** [comment]
Sure, I'll update it tomorrow morning.

**Comment by vals** [comment]
Hey, it took a while because my macOS had updated and I needed to remember how to fix gcc. But now the pip package should be updated.

**Comment by roryk** [comment]
Awesome, thanks so much Valentine.

**Comment by magali** [comment]
Hi guys,

Thanks for a quick answer. The update does not seem to be pushed onto git though (last commit in February), right?

Thanks,
Magali

**Comment by roryk** [comment]
Yeah, we haven't made a release that last commit-- but if you aren't using that feature it won't matter.
