### ISSUE TITLE
tagcount error : AttributeError

### ISSUE THREAD

**Issue by elfore** [vals/umis#57]
I am right now using this command `umis tagcount pseudoalignments.bam result.txt`.
`pseudoalignments.bam` is output of kallisto.
However, I keep getting errors:
```
INFO:umis.umis:Reading optional files

INFO:umis.umis:Tallying evidence
Traceback (most recent call last):
  File "/home5/jyangbn/.conda/envs/py2/bin/umis", line 11, in <module>
    load_entry_point('umis==1.0.3', 'console_scripts', 'umis')()
  File "/home5/jyangbn/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home5/jyangbn/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home5/jyangbn/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home5/jyangbn/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home5/jyangbn/.conda/envs/py2/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home5/jyangbn/.conda/envs/py2/lib/python2.7/site-packages/umis/umis.py", line 583, in tagcount
    CB = match.group('CB')
AttributeError: 'NoneType' object has no attribute 'group'
```

I tried python 3.6.7 and python 2.7.15 with umis 1.0.3(installed from conda), neither of them works. Could you please help me to figure this out? 

The fastq file is 20311_merged_transformed.fastq.gz from session E-MTAB-5480, then I run `kallisto quant -i reference/ercc.idx --pseudobam --single -l 180 -s 20 -o 20311_out E-MTAB-5480/20311_merged_transformed.fastq.gz` to get this bam file `pseudoalignments.bam`.
Because I have the cell barcodes I need to maintain so that I start with `umis tagcount` instead of filtering. I am attempting to extract the original molecular information (read count) not UMI count for 10X data. This is my whole processing.

Thanks for any information you may provide.

**Comment by roryk** [comment]
It looks like the transformed file does not have cellular barcodes in the FASTQ header with the format **CELL_THEBARCODE**. If you post the first read of your transformed FASTQ file we can give more information.

**Comment by elfore** [comment]
This is the fastq data I have
![image](https://user-images.githubusercontent.com/8056824/57522993-4d228380-7356-11e9-9b9e-8a6f5d17bcf9.png)

Seems like the barcode and UMI are provided?

Oh, right. Another thing is that since my focus is on ERCC sequence, so the reference contains only ERCC fa sequence.

**Comment by roryk** [comment]
Thanks-- could you put up a snippet of your BAM file somewhere for us to look at?

**Comment by elfore** [comment]
You are so nice to help me with it. I share a link here ( https://hkustconnect-my.sharepoint.com/:u:/g/personal/jyangbn_connect_ust_hk/Ef0zlhnuVhVHvvxv_oLd5kEBc3BV2i87WZ6jKoLVJPgSnw?e=qgOCmb )

I select the top 10 lines of bam file and save it as a sam file above. Hope it can help.

**Comment by roryk** [comment]
Gotcha, it looks like either the read names were stripped from these, or kallisto doesn't put the entire read name in the read name field. Since the full read name is not there, the cell barcode and umi fields are missing from the BAM file, so umis won't work the output from kallisto when it is run like this. Could you use rapmap instead of kallisto? That will definitely work. To run kallisto in single-cell mode you'd have to make a third file that has the UMI for each read and break up your FASTQ file into a separate file for each cell.

**Comment by elfore** [comment]
Thank you going through all the details, this fastq is quite different from I got before which is seperated by cells. I will try RapMap and see how it goes. Thank you for your time.

**Comment by elfore** [comment]
Even though I tried RapMap for psudomaping, I still couldn't get a bam file with full read name -- the cell barcode and umi fields are missing, then I got the same error when I run umis tagcount.  I am not sure about the right parameter, could you please help me to figure out a way to get full name reads in bam/sam file? Should I try demultiplexing or umis kallisto to divide the fastq file by cell barcode? Thanks for your help during this whole time.

Command I use for RapMap (rapmap 0.6.0) is 
```sh
rapmap quasimap -i reference/ref_index/ -r E-MTAB-5480/20311_merged_transformed.fastq.gz -t 20 -o rapmap_output/mapped_reads_311.sam
```
Bam file is like this:

```sh
@HD     VN:1.0  SO:unknown
@SQ     SN:ERCC-00002   LN:1037
@SQ     SN:ERCC-00003   LN:999
@SQ     SN:ERCC-00004   LN:499
 ...

ERR1876145.157  0       ERCC-00096      912     255     98M     *       0       0     NGCGCACAAGCACGATCGGCTCCTAATAGGAGGTGAATTAGATTAGGGAAAAGATCGGGATGCTACTAGTTTACTGCGTCACGCTGAGGGACTCATCCT      *       NH:i:1  HI:i:1  AS:i:0
ERR1876145.158  0       ERCC-00074      308     255     98M     *       0       0       NGAGGCATCTATCACATAAGGCATCATTATAACTAAAAATGGGGATATATTCCTTATAAACTACTGCTAAGACAGCTAAGAAAGCTCCAATTGGTAGAG      *       NH:i:1  HI:i:1  AS:i:0
```

**Comment by roryk** [comment]
I see-- it looks like because the read names have a space in them, the aligners are using that as the read name instead of the whole thing so the barcode information is not getting propagated. If you replace the spaces in your read names with a : or a _, that should fix this problem.

**Comment by elfore** [comment]
Thank you so much, it works!

**Comment by roryk** [comment]
Awesome! Thanks for following up.
