### ISSUE TITLE
cell barcode question

### ISSUE THREAD

**Issue by skytguuu** [vals/umis#59]
Hi,

Recently I tried to analyze scRNA-seq data produced by mcSCRB-seq. Because I have valid cell barcode file, so I did not need to identify the cell barcode in step2. Is any possible your tool could use the reference barcode file to extract the reads? I tried use " umi_tools extract" with --whitelist=MY_REF_INDEX, however it still failed. 
Could you give me some suggestions?

Thank you!

**Comment by roryk** [comment]
Hi @skytguuu,

Could you describe what FASTQ files you have and where the UMI/cellular barcodes are in them?

**Comment by skytguuu** [comment]
Hi,
My fastq files is almost 150bp base. Position 1-6  is as the cellular barcode and positions 9-16 is as the UMI. Followed is my fastq file:
###############
@E00477:517:H3CN7CCX2:4:1101:23084:1432 1:N:0:CTCTCT
NGCATGTGTCTACTAGTTTTTTTGTTTTTTTTTTTTTTTTTTTTTTTTAAGTAAACGCTTCCGGGCCCGCGGGGGACTCAGGTTAGAGCATCGAGGGGGGGGCCGGGAGGCAAGGGGGGGGGGTGGGCGGTGACTCGCGCTGGGGGGGAC
+
#AAFFJJJJJJFJJFJ77FFFJJJJJAJJJJJJJJJJJJJJJJJJJJ--<<7-<J-<-<F--7-7-AJ<77AA-7A-7--7-7-7--<-7<<--<<JFFJF--7A-77AJAF--<7A-7<FJ-7-AJ7-AAJ------))))))))--)-
###############
Thanks for your help!
Best

**Comment by roryk** [comment]
Heya-- are these single-end reads then? Or do you have paired reads? Usually SCRB-seq has the first read as you described, and the second read is the biological read. Is that the case with your experiment?

**Comment by skytguuu** [comment]
yes，I got two fastq files.R1 and R2, usually R2 was used to do the mapping.





发自我的iPhone


------------------ Original ------------------

**Comment by roryk** [comment]
Hi @skytguuu,

I see. The first step will be to stick the UMI and the barcode in your FASTQ name for R2, by running this:

```
umis fastqtransform examples/SCRB-Seq/transform.json fastq1 fastq2 > your-sample-transformed.fq
```

this will stick the cellular barcode and UMI in the read name.

Then you want to take your list of good cellular barcodes and do:

```
umis cb_filter --nedit 1 --bc1 your-barcode-file.txt your-sample-transformed.fq > your-sample-filtered.fq
```

This will remove all of the barcodes from your-sample-transformed.fq that are not one of the barcodes listed in your-barcode-file.txt, but will fix ones that are one edit distance away from a known barcode and you'll be left with just barcodes that are in your-barcode-file.txt. Does that help you get going?

**Comment by skytguuu** [comment]
Hi,
It worked. Thanks for your help!

**Comment by roryk** [comment]
Great! Glad that got you going. Thanks for following up!
