### ISSUE TITLE
tagcount with --genemap option

### ISSUE THREAD

**Issue by mmikedis** [vals/umis#62]
Hi,

I'm having a problem using umi tagcount with a genemap. I can run the following command without a gene map successfully: 

umis tagcount pseudoalignments.bam sample1.gene.cb.counts.txt

But the addition of the --genemap option gives an error: 

umis tagcount --genemap genemap.txt pseudoalignments.bam sample1.gene.cb.counts.txt

head: unrecognized option '--genemap'
INFO:umis.umis:Reading optional files
INFO:umis.umis:Tallying evidence
INFO:umis.umis:Processed 1000000 alignments, kept 791808.
INFO:umis.umis:208192 were filtered for being unmapped.
INFO:umis.umis:Processed 2000000 alignments, kept 1584028.
INFO:umis.umis:415972 were filtered for being unmapped.
INFO:umis.umis:Processed 3000000 alignments, kept 2379834.
INFO:umis.umis:620166 were filtered for being unmapped.
INFO:umis.umis:Processed 4000000 alignments, kept 3174835.
INFO:umis.umis:825165 were filtered for being unmapped.
INFO:umis.umis:Processed 5000000 alignments, kept 3969309.
INFO:umis.umis:1030691 were filtered for being unmapped.
INFO:umis.umis:Processed 6000000 alignments, kept 4760607.
INFO:umis.umis:1239393 were filtered for being unmapped.
INFO:umis.umis:Processed 7000000 alignments, kept 5552449.
INFO:umis.umis:1447551 were filtered for being unmapped.
INFO:umis.umis:Processed 8000000 alignments, kept 6349186.
INFO:umis.umis:1650814 were filtered for being unmapped.
INFO:umis.umis:Processed 9000000 alignments, kept 7143504.
INFO:umis.umis:1856496 were filtered for being unmapped.
INFO:umis.umis:Processed 10000000 alignments, kept 7937942.
INFO:umis.umis:2062058 were filtered for being unmapped.
INFO:umis.umis:Tally done - 1.07e+02s, 5,643,231 alns/min
INFO:umis.umis:Collapsing evidence
INFO:umis.umis:Writing evidence
Traceback (most recent call last):
  File "/usr/local/bin/python3.6/umis", line 11, in <module>
    load_entry_point('umis==1.0.3', 'console_scripts', 'umis')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/umis/umis.py", line 653, in tagcount
    genes = expanded.ix[genes.index]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 126, in __getitem__
    return self._getitem_axis(key, axis=axis)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1088, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1205, in _getitem_iterable
    raise_missing=False)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError:['***'] not in index"]

The *** in the last line is a list of all of the gene names in my genemap file. 

My genemap file looks like this (tab delimited): 
ENST00000456328 DDX11L1
ENST00000450305 DDX11L1
ENST00000488147 WASH7P
ENST00000619216 MIR6859-1
ENST00000473358 RP11-34P13.3

And my bam file looks like this: 
SRR8363321.42:CELL_CTCATTATCTTTACGT:UMI_ATAGGCTGTA  0 ENST00000379715 544 255 98M * 0 0 GTCTTCATCAAGAACAGACTATATACTAATTCCCACTAGAAGCTGTCCATGCCATACAGAAGATCTATTAAAAATGTTTTAAATGGAAAATGTACTCT  AA<7<FJJJFJFFJJJ<-A-FJJJJA<<JFJJFFFFAFAJJ<FJJ7FJJJFJJF-<FFJFFFFAF-FJJFAJAJJJJFJJFJJJJFJ<-77FJJJF7A  NH:i:1  ZW:f:1
SRR8363321.44:CELL_TCGGGACAGCCAGTAG:UMI_CTATTAGCCC  4 * 0 0 * * 0 0 TGCCTTGGCCTCCCAAAGTGTTGGGATTACAGGTGTGAGCCACCATGCCCGGCCAAGACATTTTATTACTAAGAGAATTGCAGTGTGCTATGAGGGTA  AA<AFJF-FJJFJJJJJJAFFFAFAJJJJJJJJFJJJFJJJJJJJFJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJFJFJJJAJFFFFJJJJFJF<J
SRR8363321.45:CELL_GGGCACTGTGTCAATC:UMI_CTAACCTAAT  256 ENST00000323345 551 255 98M * 0 0 GTCGTAAAATGGGGGTCCCTTACTGCATTATCAAGGGAAAGGCAAGACTGGGACGTCTAGTCCACAGGAAGACCTGCACCACTGTCGCCTTCACACAG  A7<AFJJJJJJJJ<F7A<JAFJFFJJJJJJJJJJJJJJJJJJJJJJJJJJJA<JJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJ  NH:i:2  ZW:f:0.0285953

Thanks for the help,
maria

**Comment by roryk** [comment]
Hi Maria,

Sorry for the problem. Hm. You have a pretty old version of umis, it looks like v1.0.3. If you update to 1.0.6 do you still run into this problem?

**Comment by mmikedis** [comment]
Thanks for the suggestion. I've updated to v.1.0.6 but I'm still having the same problem.  The error output is: 

INFO:umis.umis:Reading optional files
INFO:umis.umis:Tallying evidence
INFO:umis.umis:Processed 1000000 alignments, kept 791808.
INFO:umis.umis:208192 were filtered for being unmapped.
INFO:umis.umis:Processed 2000000 alignments, kept 1584028.
INFO:umis.umis:415972 were filtered for being unmapped.
INFO:umis.umis:Processed 3000000 alignments, kept 2379834.
INFO:umis.umis:620166 were filtered for being unmapped.
INFO:umis.umis:Processed 4000000 alignments, kept 3174835.
INFO:umis.umis:825165 were filtered for being unmapped.
INFO:umis.umis:Processed 5000000 alignments, kept 3969309.
INFO:umis.umis:1030691 were filtered for being unmapped.
INFO:umis.umis:Processed 6000000 alignments, kept 4760607.
INFO:umis.umis:1239393 were filtered for being unmapped.
INFO:umis.umis:Processed 7000000 alignments, kept 5552449.
INFO:umis.umis:1447551 were filtered for being unmapped.
INFO:umis.umis:Processed 8000000 alignments, kept 6349186.
INFO:umis.umis:1650814 were filtered for being unmapped.
INFO:umis.umis:Processed 9000000 alignments, kept 7143504.
INFO:umis.umis:1856496 were filtered for being unmapped.
INFO:umis.umis:Processed 10000000 alignments, kept 7937942.
INFO:umis.umis:2062058 were filtered for being unmapped.
INFO:umis.umis:Tally done - 1.04e+02s, 5,772,446 alns/min
INFO:umis.umis:Collapsing evidence
INFO:umis.umis:Writing evidence
Traceback (most recent call last):
  File "/usr/local/bin/python3.6/umis", line 11, in <module>
    load_entry_point('umis==1.0.6', 'console_scripts', 'umis')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/umis-1.0.6-py3.6-linux-x86_64.egg/umis/umis.py", line 656, in tagcount
    genes = expanded.ix[genes.index]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 126, in __getitem__
    return self._getitem_axis(key, axis=axis)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1088, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1205, in _getitem_iterable
    raise_missing=False)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "[<list of all genes in genemap>] not in index"

**Comment by roryk** [comment]
Could you send along like 40k lines of your transformed FASTQ file and your
genemap file so I can take a look?

**Comment by mmikedis** [comment]
You can download the files from here: https://www.dropbox.com/sh/3c5yilft3ts27o2/AAB_4vahMS2ZttOhEjFEETnNa?dl=0

Thanks for taking a look!

**Comment by roryk** [comment]
Hi Maria!

So sorry, I am dumb-- I asked for the wrong thing. Could you send me around 40k lines of the BAM/SAM file you are looking at.

**Comment by mmikedis** [comment]
Sorry, for the delayed reply; I somehow missed your last message. I put my sam file with 40k lines in the Dropbox folder above.
Thanks!

**Comment by roryk** [comment]
haha, ok last thing:  I also need the header for that file-- when you grab the small subset, could you put that up with `samtools view -H`?

**Comment by mmikedis** [comment]
I've updated the sam file so that it contains all of the original header, as well as the first 40k read alignment lines.
