### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by mfansler** [vals/umis#69]
The internal version used for output was not updated, so that `umis version` still reports `1.0.7`.

https://github.com/vals/umis/blob/e6e984341b387031a0f162f170a116db61041d88/umis/umis.py#L27

**Comment by mjsteinbaugh** [comment]
This issue is still relevant for 1.0.9

**Comment by mjsteinbaugh** [comment]
Also `setup.py` is versioned as 1.0.8 for the 1.0.9 release

https://github.com/vals/umis/blob/v1.0.9/setup.py#L11
