### ISSUE TITLE
Ensure proper version

### ISSUE THREAD

**Issue by asee-imagia** [vals/umis#71]
Hi @roryk! 

Would it be possible to ensure that the 1.0.9 _release_ and _tag_ both point to the commit that fixed the versioning (https://github.com/vals/umis/pull/70)?

Thank you for being so responsive, we really appreciate it!

**Comment by roryk** [comment]
Thank you! Sorry for missing updating the version, I was rushing. I updated the tag, which should both point to the right commit now.

**Comment by asee-imagia** [comment]
Thank you for being so responsive @roryk! Just to let you know: While this did indeed properly update the release and tag so that they both point to the commit with the proper versioning, the data on bioconda was not updated: 
``` shell
$ conda list | grep umis
umis                      1.0.9            py37h8902056_0    bioconda
$ umis version
1.0.7
```
